SELECT CURRENT_USER();

USE ROLE ACCOUNTADMIN;

GRANT ROLE HERMES_MCP_ROLE TO USER ANASTAS;
ALTER USER ANASTAS SET DEFAULT_ROLE = HERMES_MCP_ROLE;

CREATE OR REPLACE SECURITY INTEGRATION CLAUDE_MCP_OAUTH
  TYPE = OAUTH
  ENABLED = TRUE
  OAUTH_CLIENT = CUSTOM
  OAUTH_CLIENT_TYPE = 'CONFIDENTIAL'
  OAUTH_REDIRECT_URI = 'https://claude.ai/api/mcp/auth_callback'
  OAUTH_ISSUE_REFRESH_TOKENS = TRUE
  OAUTH_REFRESH_TOKEN_VALIDITY = 7776000
  PRE_AUTHORIZED_ROLES_LIST = ('HERMES_MCP_ROLE');

SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('CLAUDE_MCP_OAUTH');

SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('CLAUDE_MCP_OAUTH');

USE ROLE ACCOUNTADMIN;
ALTER SECURITY INTEGRATION CLAUDE_MCP_OAUTH REFRESH OAUTH_CLIENT_SECRET;
SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('CLAUDE_MCP_OAUTH');

SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();

USE ROLE ACCOUNTADMIN;
ALTER SECURITY INTEGRATION CLAUDE_MCP_OAUTH SET
  OAUTH_ALTERNATE_REDIRECT_URIS = (
    'https://claude.com/api/mcp/auth_callback',
    'https://claude.ai/api/mcp/auth_callback'
  );

DESC SECURITY INTEGRATION CLAUDE_MCP_OAUTH;

USE ROLE ACCOUNTADMIN;

ALTER SECURITY INTEGRATION CLAUDE_MCP_OAUTH SET
  IS_AGENTIC = TRUE,
  OAUTH_ANY_ROLE_MODE = 'ENABLE',
  OAUTH_USE_SECONDARY_ROLES = 'IMPLICIT';

DESC SECURITY INTEGRATION CLAUDE_MCP_OAUTH;

SELECT EVENT_TIMESTAMP, USER_NAME, FIRST_AUTHENTICATION_FACTOR,
       IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
WHERE EVENT_TIMESTAMP >= DATEADD('hour', -1, CURRENT_TIMESTAMP())
ORDER BY EVENT_TIMESTAMP DESC
LIMIT 20


USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS HERMES_MCP;

CREATE OR REPLACE MCP SERVER HERMES_MCP.PUBLIC.CLAUDE_SQL FROM SPECIFICATION $$
tools:
  - name: "run-sql"
    type: "SYSTEM_EXECUTE_SQL"
    title: "Execute SQL"
    description: "Execute SQL statements in Snowflake"
$$;

GRANT USAGE ON DATABASE HERMES_MCP                      TO ROLE HERMES_MCP_ROLE;
GRANT USAGE ON SCHEMA   HERMES_MCP.PUBLIC               TO ROLE HERMES_MCP_ROLE;
GRANT USAGE ON MCP SERVER HERMES_MCP.PUBLIC.CLAUDE_SQL  TO ROLE HERMES_MCP_ROLE;

ALTER USER ANASTAS ADD PROGRAMMATIC ACCESS TOKEN claude_code
  ROLE_RESTRICTION = 'HERMES_MCP_ROLE'
  DAYS_TO_EXPIRY   = 90;


USE ROLE ACCOUNTADMIN;
ALTER USER ANASTAS SET DEFAULT_WAREHOUSE = COMPUTE_WH;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HERMES_MCP_ROLE;

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE AUTHENTICATION POLICY HERMES_MCP.PUBLIC.PAT_NO_NETWORK_POLICY
  PAT_POLICY = (NETWORK_POLICY_EVALUATION = NOT_ENFORCED);

ALTER USER ANASTAS SET AUTHENTICATION POLICY HERMES_MCP.PUBLIC.PAT_NO_NETWORK_POLICY;


SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();

USE ROLE ACCOUNTADMIN;
ALTER SECURITY INTEGRATION CLAUDE_MCP_OAUTH SET PRE_AUTHORIZED_ROLES_LIST = ();
SELECT SYSTEM$SHOW_OAUTH_CLIENT_SECRETS('CLAUDE_MCP_OAUTH');


SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_VERSION()

USE ROLE ACCOUNTADMIN;
ALTER USER ANASTAS SET DEFAULT_ROLE = HERMES_MCP_ROLE;

USE ROLE ACCOUNTADMIN;
ALTER USER ANASTAS SET DEFAULT_ROLE = HERMES_MCP_ROLE;

SELECT CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_VERSION()

USE ROLE ACCOUNTADMIN;
GRANT CREATE SCHEMA ON DATABASE HERMES_MCP TO ROLE HERMES_MCP_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE
  ON SCHEMA HERMES_MCP.PUBLIC TO ROLE HERMES_MCP_ROLE;

GRANT USAGE  ON DATABASE <DB>                 TO ROLE HERMES_MCP_ROLE;
GRANT USAGE  ON ALL SCHEMAS IN DATABASE <DB>  TO ROLE HERMES_MCP_ROLE;
GRANT SELECT ON ALL TABLES  IN DATABASE <DB>  TO ROLE HERMES_MCP_ROLE;
GRANT SELECT ON ALL VIEWS   IN DATABASE <DB>  TO ROLE HERMES_MCP_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE <DB> TO ROLE HERMES_MCP_ROLE;

USE ROLE ACCOUNTADMIN;
SHOW DATABASES;

SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, ROW_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE DELETED IS NULL AND ROW_COUNT > 0
ORDER BY ROW_COUNT DESC
LIMIT 50;


USE ROLE ACCOUNTADMIN;

-- песочница: право заводить сущности
GRANT CREATE SCHEMA ON DATABASE HERMES_MCP TO ROLE HERMES_MCP_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE
  ON SCHEMA HERMES_MCP.PUBLIC TO ROLE HERMES_MCP_ROLE;

-- демо-данные: на них удобно проверить, что чтение вообще идёт
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE HERMES_MCP_ROLE;

-- метаданные аккаунта: ACCOUNT_USAGE, история запросов и расходов
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE HERMES_MCP_ROLE;


USE ROLE ACCOUNTADMIN;
SHOW GRANTS TO ROLE HERMES_MCP_ROLE;

USE ROLE HERMES_MCP_ROLE;
USE WAREHOUSE COMPUTE_WH;

CREATE TABLE HERMES_MCP.PUBLIC.ACCESS_TEST (x INT);
INSERT INTO HERMES_MCP.PUBLIC.ACCESS_TEST VALUES (1);
SELECT * FROM HERMES_MCP.PUBLIC.ACCESS_TEST;
DROP TABLE HERMES_MCP.PUBLIC.ACCESS_TEST;

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;



USE ROLE ACCOUNTADMIN;

-- 1. Пересоздать MCP-сервер с разрешённой записью
CREATE OR REPLACE MCP SERVER HERMES_MCP.PUBLIC.CLAUDE_SQL
FROM SPECIFICATION $$
version: 1
tools:
  - name: "run-sql"
    type: "SYSTEM_EXECUTE_SQL"
    title: "Execute SQL"
    description: "Execute SQL statements in Snowflake"
    config:
      read_only: false
      query_timeout: 300
      warehouse: "COMPUTE_WH"
$$;

-- 2. Вернуть доступ роли коннектора (идемпотентно, но обязательно проверить)
GRANT USAGE ON MCP SERVER HERMES_MCP.PUBLIC.CLAUDE_SQL TO ROLE HERMES_MCP_ROLE;

-- 3. Расширить права на запись в песочнице HERMES_MCP
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE SEQUENCE,
      CREATE FUNCTION, CREATE PROCEDURE, CREATE TASK, CREATE STREAM,
      CREATE DYNAMIC TABLE, CREATE FILE FORMAT
  ON SCHEMA HERMES_MCP.PUBLIC TO ROLE HERMES_MCP_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA HERMES_MCP.PUBLIC TO ROLE HERMES_MCP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA HERMES_MCP.PUBLIC TO ROLE HERMES_MCP_ROLE;

GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE HERMES_MCP_ROLE;
